# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Light Scheduler
version: "0.2.1"
slug: light_scheduler
description: Schedule on/off, brightness and color temperature of your lights on a visual daily/weekly timeline.
url: "https://github.com/wmvos/light-scheduler/tree/main/light_scheduler"
arch:
  - aarch64
  - amd64
init: false
ingress: true
panel_icon: "mdi:lightbulb"
map:
  - config:rw
homeassistant_api: true
long_lived_tokens: true
options:
  light: ""
  tick_interval:
    int: 30
schema:
  light: "entity(light.*)"
  tick_interval:
    int: "10|60"
